# Generated by Django 4.2.3 on 2023-07-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BikeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('color', models.ManyToManyField(blank=True, related_name='bike_color', to='store.color')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gor', 'Gorniy'), ('sport', 'Sportivniy')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('wheels', models.FloatField(default=20.0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bikebrand')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bikeframe')),
            ],
        ),
    ]
