# Generated by Django 4.2.3 on 2023-07-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='frame',
        ),
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ManyToManyField(blank=True, related_name='bike_frame', to='store.bikeframe'),
        ),
    ]
