# Generated by Django 4.2.3 on 2023-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_bikeframe_color_bike_color_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
